Repository TEAM-DDIS/be14-4th-DDIS-FE, pull requests merged in 2025-04, with the labels that each got.

#2 [chore] vue 세팅
  .gitignore
  .vscode/extensions.json
  index.html
  jsconfig.json
  package.json
  public/favicon.ico
  src/App.vue
  src/assets/base.css
  src/assets/logo.svg
  src/assets/main.css
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.js
  vite.config.js
Labels: ⚙ Chore

#4 [feat] calendar 컴포넌트 구현
  package-lock.json
  package.json
  src/App.vue
  src/assets/icons/setting-icon.svg
  src/components/calendar/Calendar.vue
  src/components/stone/Stone01.vue
  src/components/stone/Stone02.vue
  src/components/stone/Stone03.vue
  src/components/stone/Stone04.vue
  src/components/stone/Stone05.vue
  src/main.js
  src/pages/MyPage.vue
Labels: ✨ Feat

#6 [feat] header 컴포넌트 구현
  src/assets/icons/alert-icon.svg
  src/assets/icons/dm-icon.svg
  src/assets/icons/logout-icon.svg
  src/assets/icons/search-icon.svg
  src/assets/images/header-profile.png
  src/assets/images/logo.png
  src/components/header/Header.vue
  src/pages/MyPage.vue
Labels: ✨ Feat

#7 [feat] 마이페이지 프로필 추가
  src/pages/MyPage.vue
Labels: ✨ Feat

#8 [chore] json 서버, 라우터 세팅
  package-lock.json
  package.json
  server/mockup.json
  src/App.vue
  src/components/report/ReportBox.vue
  src/components/report/ReportModal.vue
  src/main.js
  src/pages/PersonalTodoPage.vue
  src/pages/ReportPage.vue
  src/router/index.js
Labels: ⚙ Chore

#12 [feat] footer 구현
  src/App.vue
  src/components/footer/Footer.vue
  src/pages/ReportPage.vue
Labels: ✨ Feat

#15 [feat] 로그인 페이지 구현
  src/assets/icons/google-icon.svg
  src/assets/icons/invisible-icon.svg
  src/assets/icons/kakao-icon.svg
  src/assets/icons/visible-icon.svg
  src/components/header/LoginHeader.vue
  src/pages/LoginPage.vue
  src/router/index.js
Labels: ✨ Feat

#20 [feat] 신고 관리 페이지 구현
  server/mockup.json
  src/assets/icons/check-icon.svg
  src/assets/icons/double-left-icon.svg
  src/assets/icons/double-right-icon.svg
  src/assets/icons/left-icon.svg
  src/assets/icons/reject-icon.svg
  src/assets/icons/right-icon.svg
  src/components/header/AdminHeader.vue
  src/components/header/Header.vue
  src/components/pagenation/Pagenation.vue
  src/components/report/ReportBox.vue
  src/pages/ReportPage.vue
Labels: ✨ Feat

#24 [feat] 신고 모달 구현
  src/components/report/ReportModal.vue
Labels: ✨ Feat

#26 [feat] 팔로워, 팔로잉 모달 구현
  server/mockup.json
  src/components/follow/FollowBox.vue
  src/components/follow/Follower.vue
  src/components/follow/Following.vue
Labels: ✨ Feat

#30 [FEAT] 회원가입 UI 구현
  src/pages/SignUpPage.vue
  src/router/index.js
Labels: ✨ Feat

#34 [refactor] 신고 관리 페이지 백엔드 연동
  src/components/report/ReportBox.vue
  src/pages/ReportPage.vue
Labels: 🔧 Refactor

#35 [feat] 회원가입 프론트엔드 백엔드 연동
  src/pages/SignUpPage.vue
Labels: ✨ Feat

#37 [feat] login 프론트엔드 백엔드 연동
  src/pages/LoginPage.vue
Labels: ✨ Feat

#42 [feat] 신고 등록 백엔드 연동
  src/components/report/ReportModal.vue
  src/utils/token.js
Labels: ✨ Feat

#43 [feat] 아이디 찾기 UI 구성 및 백엔드 연동
  src/pages/FindIdPage.vue
  src/router/index.js
Labels: ✨ Feat

#45 [feat] 개인 todo 일부 UI 구현 완료
  package-lock.json
  server/mockup.json
  src/App.vue
  src/assets/icons/todo-global.svg
  src/assets/icons/todo-lock.svg
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/PinnedTodoList.vue
  src/components/calendar/TodoAddModal.vue
  src/components/calendar/TodoItem.vue
  src/components/calendar/TodoList.vue
  src/components/header/Header.vue
  src/components/header/LoginHeader.vue
  src/main.js
  src/pages/PersonalTodoPage.vue
  src/router/index.js
Labels: ✨ Feat

#46 [fix] 수정 2
  src/pages/FindIdPage.vue
Labels: ✨ Feat

#48 [feat] 회원 정보 수정 페이지 UI 구현
  src/pages/ModifyProfilePage.vue
  src/router/index.js
Labels: ✨ Feat

#52 [fix] 수정
  package.json
Labels: ✨ Feat

#55 [feat] 비밀번호 변경 페이지 UI 및 백엔드 연동
  src/pages/ModifyPasswordPage.vue
  src/pages/ModifyProfilePage.vue
  src/pages/SignUpPage.vue
Labels: ✨ Feat

#57 [feat] 개인 Todo 백엔드 연동 (이슈 참고)
  server/mockup.json
  src/components/calendar/PersonalCalendar.vue
  src/components/calendar/PinnedTodoList.vue
  src/components/calendar/TodoItem.vue
  src/components/calendar/TodoList.vue
  src/pages/PersonalTodoPage.vue
Labels: ✨ Feat

#59 [feat] 1차 수정
  src/pages/LoginPage.vue
  src/router/index.js
Labels: ✨ Feat

#61 Feat/kj/set pinia
  package-lock.json
  package.json
  src/App.vue
  src/components/header/Header.vue
  src/components/inquiry/InquiryDetailPage.vue
  src/components/inquiry/InquiryDetailPageAdmin.vue
  src/components/notice/NoticeDetailPage.vue
  src/components/notice/NoticeDetailPageAdmin.vue
  src/main.js
  src/pages/ChatRoomPage.vue
  src/pages/FindIdPage.vue
  src/pages/InquiryPage.vue
  src/pages/LoginPage.vue
  src/pages/ModifyPasswordPage.vue
  src/pages/ModifyProfilePage.vue
  src/pages/NoticePage.vue
  src/pages/PersonalTodoPage.vue
  src/pages/ReportPage.vue
  src/pages/RoomListPage.vue
  src/pages/ShareRoomPage.Vue
  src/router/index.js
  src/stores/useAuthStore.js
  src/utils/axios.js
Labels: ✨ Feat
